bin_path: ./bin
data_dir: data

runtime:
  enabled: true
  data_file: runtime.txt
  samples: 1000000
  solvers: [Newton, Broyden]
  integrators: [ForwardEuler, AB2, AB3, AB4, AB5, RK2, RK3, RK4]
  h: 1e-3

stiffness:
  enabled: true
  threads: 8
  samples_per_thread: 2500000
  solver: Broyden
  integrator: AB4
  h: 1e-3

finite_differences:
  enabled: true
  samples: 1000000
  solver: Broyden
  integrator: AB4
  h: 1e-3
  j_start: 1.0
  j_step: 0.25
  j_end: 10.0

visualizations:
  enabled: true